all: st

st: speedtest.cpp ilist.h linkedlist.h arraylist.h plusonearraylist.h plustenarraylist.h doublingarraylist.h linklistImpl.h arrayImpl.h stack.h
	g++ -g speedtest.cpp -o st

clean:
	rm -rf *o hello
